### ISSUE TITLE
Wrong callback function index

### ISSUE THREAD

**Issue by vaerh** [tryffel/twidgets#1]
Hi, 
The AddRow function uses the [wrong variable for callback](https://github.com/tryffel/twidgets/blob/208fa4e3372167ce9e6329cb4a547b2dfad9a26c/table.go#L146). The row number is returned instead of the column number.

The implementation of the error hit [bookmarker](https://github.com/tryffel/bookmarker/blob/a3e4f99ae4c292a320b3cda4dd493d36d7eba767/ui/bookmarks.go#L193)

**Comment by tryffel** [comment]
Thanks for letting me know! I'll fix it when I have more time. Also PR is welcome.
